### ISSUE TITLE
add some tests

### ISSUE THREAD

**Issue by voku** [JBlond/PHP-XSS-Filter#1]
Hi, I have ported the XSS-Filter from "CodeIgniter" and added some more tests, maybe you can use these tests?

-> https://github.com/voku/anti-xss/blob/master/tests/XssTest.php

Mfg Lars

**Comment by JBlond** [comment]
Feel free to fork this repo, integrate the tests and open a pull request

**Comment by voku** [comment]
I added the testes yesterday, but your results are very different, so I would have to adjust all the tests :/
